[2025-03-23T18:09:01.982+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-23T18:09:02.013+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_etl_pipeline.transformation scheduled__2025-03-22T00:00:00+00:00 [queued]>
[2025-03-23T18:09:02.021+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_etl_pipeline.transformation scheduled__2025-03-22T00:00:00+00:00 [queued]>
[2025-03-23T18:09:02.021+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-03-23T18:09:02.054+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transformation> on 2025-03-22 00:00:00+00:00
[2025-03-23T18:09:02.059+0000] {standard_task_runner.py:63} INFO - Started process 224 to run task
[2025-03-23T18:09:02.062+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spotify_etl_pipeline', 'transformation', 'scheduled__2025-03-22T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/data_pipeline_dag.py', '--cfg-path', '/tmp/tmpsqpgl4tz']
[2025-03-23T18:09:02.064+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask transformation
[2025-03-23T18:09:02.148+0000] {task_command.py:426} INFO - Running <TaskInstance: spotify_etl_pipeline.transformation scheduled__2025-03-22T00:00:00+00:00 [running]> on host ffe4e0703eb1
[2025-03-23T18:09:02.272+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='lobobranco' AIRFLOW_CTX_DAG_ID='spotify_etl_pipeline' AIRFLOW_CTX_TASK_ID='transformation' AIRFLOW_CTX_EXECUTION_DATE='2025-03-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-22T00:00:00+00:00'
[2025-03-23T18:09:02.273+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-23T18:09:02.296+0000] {data_pipeline_dag.py:77} INFO - Transforming data from file: None
[2025-03-23T18:09:02.297+0000] {baseoperator.py:400} WARNING - SparkSubmitOperator.execute cannot be called outside TaskInstance!
[2025-03-23T18:09:02.307+0000] {spark_submit.py:305} INFO - Could not load connection string spark_default, defaulting to yarn
[2025-03-23T18:09:02.308+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-23T18:09:02.308+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_pipeline_dag.py", line 93, in spark_dtransformation
    spark_submit_task.execute(kwargs)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 539, in submit
    spark_submit_cmd = self._build_spark_submit_command(application)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 474, in _build_spark_submit_command
    self.log.info("Spark-Submit cmd: %s", self._mask_cmd(connection_cmd))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 378, in _mask_cmd
    " ".join(connection_cmd),
    ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 13: expected str instance, NoneType found
[2025-03-23T18:09:02.323+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spotify_etl_pipeline, task_id=transformation, run_id=scheduled__2025-03-22T00:00:00+00:00, execution_date=20250322T000000, start_date=20250323T180902, end_date=20250323T180902
[2025-03-23T18:09:02.367+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task transformation (sequence item 13: expected str instance, NoneType found; 224)
[2025-03-23T18:09:02.395+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-03-23T18:09:02.418+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-23T18:09:02.445+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
